targets:
  # PDF handouts for students:
  - name: handout
    format: pdf
    command:
      pandoc --from=markdown+emoji
             --pdf-engine=xelatex
             --output=%o
             --to=latex
             --toc
             --toc-depth=2
             --top-level-division=chapter
             --number-sections
             %i

  # PDF beamer slides without notes:
  - name: slides
    format: pdf
    remove-divs: [ notes ]
    command:
      pandoc --from=markdown+emoji
             --pdf-engine=xelatex
             --output=%o
             --to=beamer
             --slide-level=3
             --variable=classoption:aspectratio=43
             %i

input-files:
  - courses/sql-intro.md

output-directory: build
